// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using laboratorio_web_api_istea.DAL;

#nullable disable

namespace laboratorio_web_api_istea.Migrations
{
    [DbContext(typeof(RestauranteContext))]
    partial class RestauranteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Comanda", b =>
                {
                    b.Property<int>("IdComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comanda");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComanda"));

                    b.Property<int>("IdMesa")
                        .HasColumnType("int")
                        .HasColumnName("id_mesa");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre_cliente");

                    b.HasKey("IdComanda")
                        .HasName("PK__comandas__6D6D170D8EE45A48");

                    b.HasIndex("IdMesa");

                    b.ToTable("comandas", (string)null);
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdSector")
                        .HasColumnType("int")
                        .HasColumnName("id_sector");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("usuario");

                    b.HasKey("IdEmpleado")
                        .HasName("PK__empleado__88B51394BA44895C");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSector");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.EstadosMesa", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdEstado")
                        .HasName("PK__estados___86989FB25DC000DA");

                    b.ToTable("estados_mesas", (string)null);
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.EstadosPedido", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdEstado")
                        .HasName("PK__estados___86989FB22B850469");

                    b.ToTable("estados_pedidos", (string)null);
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mesa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMesa"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMesa")
                        .HasName("PK__mesas__68A1E159EA69519A");

                    b.HasIndex("IdEstado");

                    b.ToTable("mesas", (string)null);
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_finalizacion");

                    b.Property<int>("IdComanda")
                        .HasColumnType("int")
                        .HasColumnName("id_comanda");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("IdPedido")
                        .HasName("PK__pedidos__6FF014893198D858");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdProducto");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdSector")
                        .HasColumnType("int")
                        .HasColumnName("id_sector");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("IdProducto")
                        .HasName("PK__producto__FF341C0DBCB8AC7D");

                    b.HasIndex("IdSector");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdRol")
                        .HasName("PK__roles__6ABCB5E0F0DBB297");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Sectore", b =>
                {
                    b.Property<int>("IdSector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sector");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSector"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdSector")
                        .HasName("PK__sectores__3483C369F5575B44");

                    b.ToTable("sectores", (string)null);
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Comanda", b =>
                {
                    b.HasOne("laboratorio_web_api_istea.DAL.Models.Mesa", "IdMesaNavigation")
                        .WithMany("Comanda")
                        .HasForeignKey("IdMesa")
                        .IsRequired()
                        .HasConstraintName("FK__comandas__id_mes__6A30C649");

                    b.Navigation("IdMesaNavigation");
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Empleado", b =>
                {
                    b.HasOne("laboratorio_web_api_istea.DAL.Models.Role", "IdRolNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__empleados__id_ro__5FB337D6");

                    b.HasOne("laboratorio_web_api_istea.DAL.Models.Sectore", "IdSectorNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdSector")
                        .IsRequired()
                        .HasConstraintName("FK__empleados__id_se__5EBF139D");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdSectorNavigation");
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Mesa", b =>
                {
                    b.HasOne("laboratorio_web_api_istea.DAL.Models.EstadosMesa", "IdEstadoNavigation")
                        .WithMany("Mesas")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK__mesas__id_estado__6754599E");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Pedido", b =>
                {
                    b.HasOne("laboratorio_web_api_istea.DAL.Models.Comanda", "IdComandaNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdComanda")
                        .IsRequired()
                        .HasConstraintName("FK__pedidos__id_coma__6EF57B66");

                    b.HasOne("laboratorio_web_api_istea.DAL.Models.EstadosPedido", "IdEstadoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK__pedidos__id_esta__70DDC3D8");

                    b.HasOne("laboratorio_web_api_istea.DAL.Models.Producto", "IdProductoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__pedidos__id_prod__6FE99F9F");

                    b.Navigation("IdComandaNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Producto", b =>
                {
                    b.HasOne("laboratorio_web_api_istea.DAL.Models.Sectore", "IdSectorNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdSector")
                        .IsRequired()
                        .HasConstraintName("FK__productos__id_se__628FA481");

                    b.Navigation("IdSectorNavigation");
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Comanda", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.EstadosMesa", b =>
                {
                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.EstadosPedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Mesa", b =>
                {
                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Producto", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Role", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("laboratorio_web_api_istea.DAL.Models.Sectore", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
